### ISSUE TITLE
Font size selector can't work as expected

### ISSUE THREAD

**Issue by DopamineNone** [DopamineNone/MiNote#6]
Once any size is picked up, the text appear so mini:
![image](https://github.com/user-attachments/assets/e67dfb36-ca00-4a0b-8cf4-11384b8fceed)

**Comment by Fanglinrui** [comment]
Instead of using“Size adjustment” in the upper-left menu bar, tap the +-button in“Edit Font”

**Comment by DopamineNone** [comment]
Old version "Font size" is banned.
![image](https://github.com/user-attachments/assets/a6e7963b-4719-477c-a95b-870be86eab80)
